"""Template to write your model. This is the short description"""

_DESCRIPTION = """
Template to write your model. This can be written with markdown formalism. 

* **Name :**
* **Article :** 
* **Author  :** 
* **Coder   :** 

* **Supplements description :** 

**TODO:**
* DO NOT EDIT THIS FILE ! COPY AND PASTE IT THEN MODIFY THE COPY TO WRITE YOUR MODEL
"""
################# IMPORTS ##################################################
import numpy as np #(if you need exponential, pi, log, of matrix products...)
from pygemmes._models import Funcs, importmodel,mergemodel,filldimensions
from pygemmes._models import Operators as O

################## ALL THE NEW FIELDS LOGICS ###############################
_LOGICS = { 'size'        : {},
            'differential': {},
            'statevar'    : {},
            'parameter'   : {},}
'''
'p': {  'func': lambda p,inflation : p*inflation,
        'initial':1,
        'units': '$.Units^{-1}',
        'definition' : 'nominal value per physical unit produced',
        'com': 'inflation driven',
        'symbol': '$\mathcal{P}$',
        'size' : ['__ONE__','__ONE__']},
'p': { 'func' lambda p,inflation : p*inflation}, # for short
'''

################## MODELS YOU WANT TO MERGE THE NEW LOGICS INTO ############

#_LOGICS_GOODWIN,_PRESETS0= importmodel('Goodwin')
#_LOGICS = mergemodel(_LOGICS, _LOGICS_GOODWIN, verb=False) 

################## ADDING DIMENSIONS TO VARIABLES IF NOT DONE BEFORE #######
'''
Comment the line in 'Dimensions' you want to be filled by default. 
The system does not handle automatically multiple types of matrix/vector dimensions. do it manually
Modify DIM 
'''
Dimensions = { 
    #'scalar': [],
    'matrix': [],
    'vector': [],       #
}
DIM= {'scalar':['__ONE__'],
      'vector':['Nprod'],
      'matrix':['Nprod','Nprod']  }
_LOGICS=filldimensions(_LOGICS,Dimensions,DIM)

################### SUPPLEMENTS IF NEEDED ###################################
_SUPPLEMENTS={}

################### DEFIMING PRESETS WITH THEIR SUPPLEMENTS #################
_PRESETS = {
    'preset0': {
        'fields': {
            'fields1':0,
            'fields2':0,
        },
        'com': '',
        'plots': {'Var': [{'key':'',
                           'mode':False, #sensitivity, cycles
                           'log':False,
                           'idx':0, 
                           'Region':0, 
                           'tini':False, 
                           'tend':False, 
                           'title':''},
                  ],
                  'XY': [{  'x':'',
                            'y':'',
                            'color':'', 
                            'scaled':False,
                            'idx':0, 
                            'Region':0, 
                            'tini':False, 
                            'tend':False, 
                            'title':'', 
                            },
                  ],
                  'XYZ': [{ 'x':'',
                            'y':'',
                            'z':'', 
                            'color':'time', 
                            'idx':0, 
                            'Region':0, 
                            'tini':False, 
                            'tend':False, 
                            'title':''},
                  ],
                  'cycles_characteristics': [{'xaxis':'omega', 
                                              'yaxis':'employment', 
                                              'ref':'employment', 
                                              'type1':'frequency', 
                                              'normalize':False, 
                                              'Region':0, 
                                              'title':''},
                  ],
                  'plotbyunits': [{'filters_key':(),
                                   'filters_units':(),
                                   'filters_sector':(),
                                   'separate_variables':{}, 
                                   'lw':1, 
                                   'idx':0, 
                                   'Region':0, 
                                   'tini':False, 
                                   'tend':False, 
                                   'title':''}
                  ],
                  'plotnyaxis' : [{'y':[[],[]],
                                   'x':'time', 
                                   'idx':0,
                                   'Region':0,
                                   'log':False,# []
                                   'title':'', 
                                   }
                  ],    
        },
    },
}


